/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * game.java
 *
 * Created on 19 มี.ค. 2556, 14:36:44
 */
/**
 *
 * @author Lottae
 */
public class game extends javax.swing.JFrame {

    /**
     * Creates new form game
     */
    public String text = "";

    public game() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        jLayeredPane2 = new javax.swing.JLayeredPane();
        A1 = new javax.swing.JButton();
        A2 = new javax.swing.JButton();
        A3 = new javax.swing.JButton();
        A4 = new javax.swing.JButton();
        A5 = new javax.swing.JButton();
        A6 = new javax.swing.JButton();
        A7 = new javax.swing.JButton();
        A8 = new javax.swing.JButton();
        A9 = new javax.swing.JButton();
        A10 = new javax.swing.JButton();
        A11 = new javax.swing.JButton();
        A12 = new javax.swing.JButton();
        B1 = new javax.swing.JButton();
        B2 = new javax.swing.JButton();
        B3 = new javax.swing.JButton();
        B4 = new javax.swing.JButton();
        B5 = new javax.swing.JButton();
        B6 = new javax.swing.JButton();
        B7 = new javax.swing.JButton();
        B8 = new javax.swing.JButton();
        B9 = new javax.swing.JButton();
        B10 = new javax.swing.JButton();
        B11 = new javax.swing.JButton();
        B12 = new javax.swing.JButton();
        C1 = new javax.swing.JButton();
        C2 = new javax.swing.JButton();
        C3 = new javax.swing.JButton();
        C4 = new javax.swing.JButton();
        C5 = new javax.swing.JButton();
        C6 = new javax.swing.JButton();
        C7 = new javax.swing.JButton();
        C8 = new javax.swing.JButton();
        C9 = new javax.swing.JButton();
        C10 = new javax.swing.JButton();
        C11 = new javax.swing.JButton();
        C12 = new javax.swing.JButton();
        D1 = new javax.swing.JButton();
        D2 = new javax.swing.JButton();
        D3 = new javax.swing.JButton();
        D4 = new javax.swing.JButton();
        D5 = new javax.swing.JButton();
        D6 = new javax.swing.JButton();
        D7 = new javax.swing.JButton();
        D8 = new javax.swing.JButton();
        D9 = new javax.swing.JButton();
        D10 = new javax.swing.JButton();
        D11 = new javax.swing.JButton();
        D12 = new javax.swing.JButton();
        E1 = new javax.swing.JButton();
        E2 = new javax.swing.JButton();
        E3 = new javax.swing.JButton();
        E4 = new javax.swing.JButton();
        E5 = new javax.swing.JButton();
        E6 = new javax.swing.JButton();
        E7 = new javax.swing.JButton();
        E8 = new javax.swing.JButton();
        E9 = new javax.swing.JButton();
        E10 = new javax.swing.JButton();
        E11 = new javax.swing.JButton();
        E12 = new javax.swing.JButton();
        F1 = new javax.swing.JButton();
        F2 = new javax.swing.JButton();
        F3 = new javax.swing.JButton();
        F4 = new javax.swing.JButton();
        F5 = new javax.swing.JButton();
        F6 = new javax.swing.JButton();
        F7 = new javax.swing.JButton();
        F8 = new javax.swing.JButton();
        F9 = new javax.swing.JButton();
        F10 = new javax.swing.JButton();
        F11 = new javax.swing.JButton();
        F12 = new javax.swing.JButton();
        G1 = new javax.swing.JButton();
        G2 = new javax.swing.JButton();
        G3 = new javax.swing.JButton();
        G4 = new javax.swing.JButton();
        G5 = new javax.swing.JButton();
        G6 = new javax.swing.JButton();
        G7 = new javax.swing.JButton();
        G8 = new javax.swing.JButton();
        G9 = new javax.swing.JButton();
        G10 = new javax.swing.JButton();
        G11 = new javax.swing.JButton();
        G12 = new javax.swing.JButton();
        H1 = new javax.swing.JButton();
        H2 = new javax.swing.JButton();
        H3 = new javax.swing.JButton();
        H4 = new javax.swing.JButton();
        H5 = new javax.swing.JButton();
        H6 = new javax.swing.JButton();
        H7 = new javax.swing.JButton();
        H8 = new javax.swing.JButton();
        H9 = new javax.swing.JButton();
        H10 = new javax.swing.JButton();
        H11 = new javax.swing.JButton();
        javax.swing.JButton H12 = new javax.swing.JButton();
        I1 = new javax.swing.JButton();
        I2 = new javax.swing.JButton();
        javax.swing.JButton I3 = new javax.swing.JButton();
        I4 = new javax.swing.JButton();
        javax.swing.JButton I5 = new javax.swing.JButton();
        javax.swing.JButton I6 = new javax.swing.JButton();
        I7 = new javax.swing.JButton();
        I8 = new javax.swing.JButton();
        I9 = new javax.swing.JButton();
        I10 = new javax.swing.JButton();
        javax.swing.JButton I11 = new javax.swing.JButton();
        I12 = new javax.swing.JButton();
        jLayeredPane3 = new javax.swing.JLayeredPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setPreferredSize(new java.awt.Dimension(1200, 666));

        jLayeredPane2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLayeredPane2.setMinimumSize(new java.awt.Dimension(800, 650));

        A1.setLabel("A1");
        A1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                A1ActionPerformed(evt);
            }
        });
        A1.setBounds(0, 0, 74, 74);
        jLayeredPane2.add(A1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        A2.setText("A2");
        A2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                A2ActionPerformed(evt);
            }
        });
        A2.setBounds(74, 0, 74, 74);
        jLayeredPane2.add(A2, javax.swing.JLayeredPane.DEFAULT_LAYER);

        A3.setText("A3");
        A3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                A3ActionPerformed(evt);
            }
        });
        A3.setBounds(148, 0, 74, 74);
        jLayeredPane2.add(A3, javax.swing.JLayeredPane.DEFAULT_LAYER);

        A4.setText("A4");
        A4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                A4ActionPerformed(evt);
            }
        });
        A4.setBounds(222, 0, 74, 74);
        jLayeredPane2.add(A4, javax.swing.JLayeredPane.DEFAULT_LAYER);

        A5.setText("A5");
        A5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                A5ActionPerformed(evt);
            }
        });
        A5.setBounds(296, 0, 74, 74);
        jLayeredPane2.add(A5, javax.swing.JLayeredPane.DEFAULT_LAYER);

        A6.setText("A6");
        A6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                A6ActionPerformed(evt);
            }
        });
        A6.setBounds(370, 0, 74, 74);
        jLayeredPane2.add(A6, javax.swing.JLayeredPane.DEFAULT_LAYER);

        A7.setText("A7");
        A7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                A7ActionPerformed(evt);
            }
        });
        A7.setBounds(444, 0, 74, 74);
        jLayeredPane2.add(A7, javax.swing.JLayeredPane.DEFAULT_LAYER);

        A8.setText("A8");
        A8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                A8ActionPerformed(evt);
            }
        });
        A8.setBounds(518, 0, 74, 74);
        jLayeredPane2.add(A8, javax.swing.JLayeredPane.DEFAULT_LAYER);

        A9.setText("A9");
        A9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                A9ActionPerformed(evt);
            }
        });
        A9.setBounds(592, 0, 74, 74);
        jLayeredPane2.add(A9, javax.swing.JLayeredPane.DEFAULT_LAYER);

        A10.setText("A10");
        A10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                A10ActionPerformed(evt);
            }
        });
        A10.setBounds(666, 0, 74, 74);
        jLayeredPane2.add(A10, javax.swing.JLayeredPane.DEFAULT_LAYER);

        A11.setText("A11");
        A11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                A11ActionPerformed(evt);
            }
        });
        A11.setBounds(740, 0, 74, 74);
        jLayeredPane2.add(A11, javax.swing.JLayeredPane.DEFAULT_LAYER);

        A12.setText("A12");
        A12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                A12ActionPerformed(evt);
            }
        });
        A12.setBounds(814, 0, 74, 74);
        jLayeredPane2.add(A12, javax.swing.JLayeredPane.DEFAULT_LAYER);

        B1.setText("B1");
        B1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B1ActionPerformed(evt);
            }
        });
        B1.setBounds(0, 74, 74, 74);
        jLayeredPane2.add(B1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        B2.setText("B2");
        B2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B2ActionPerformed(evt);
            }
        });
        B2.setBounds(74, 74, 74, 74);
        jLayeredPane2.add(B2, javax.swing.JLayeredPane.DEFAULT_LAYER);

        B3.setText("B3");
        B3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B3ActionPerformed(evt);
            }
        });
        B3.setBounds(148, 74, 74, 74);
        jLayeredPane2.add(B3, javax.swing.JLayeredPane.DEFAULT_LAYER);

        B4.setText("B4");
        B4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B4ActionPerformed(evt);
            }
        });
        B4.setBounds(222, 74, 74, 74);
        jLayeredPane2.add(B4, javax.swing.JLayeredPane.DEFAULT_LAYER);

        B5.setText("B5");
        B5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B5ActionPerformed(evt);
            }
        });
        B5.setBounds(296, 74, 74, 74);
        jLayeredPane2.add(B5, javax.swing.JLayeredPane.DEFAULT_LAYER);

        B6.setText("B6");
        B6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B6ActionPerformed(evt);
            }
        });
        B6.setBounds(370, 74, 74, 74);
        jLayeredPane2.add(B6, javax.swing.JLayeredPane.DEFAULT_LAYER);

        B7.setText("B7");
        B7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B7ActionPerformed(evt);
            }
        });
        B7.setBounds(444, 74, 74, 74);
        jLayeredPane2.add(B7, javax.swing.JLayeredPane.DEFAULT_LAYER);

        B8.setText("B8");
        B8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B8ActionPerformed(evt);
            }
        });
        B8.setBounds(518, 74, 74, 74);
        jLayeredPane2.add(B8, javax.swing.JLayeredPane.DEFAULT_LAYER);

        B9.setText("B9");
        B9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B9ActionPerformed(evt);
            }
        });
        B9.setBounds(592, 74, 75, 75);
        jLayeredPane2.add(B9, javax.swing.JLayeredPane.DEFAULT_LAYER);

        B10.setText("B10");
        B10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B10ActionPerformed(evt);
            }
        });
        B10.setBounds(666, 74, 74, 74);
        jLayeredPane2.add(B10, javax.swing.JLayeredPane.DEFAULT_LAYER);

        B11.setText("B11");
        B11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B11ActionPerformed(evt);
            }
        });
        B11.setBounds(740, 74, 74, 74);
        jLayeredPane2.add(B11, javax.swing.JLayeredPane.DEFAULT_LAYER);

        B12.setText("B12");
        B12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B12ActionPerformed(evt);
            }
        });
        B12.setBounds(814, 74, 74, 74);
        jLayeredPane2.add(B12, javax.swing.JLayeredPane.DEFAULT_LAYER);

        C1.setText("C1");
        C1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                C1ActionPerformed(evt);
            }
        });
        C1.setBounds(0, 148, 74, 74);
        jLayeredPane2.add(C1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        C2.setText("C2");
        C2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                C2ActionPerformed(evt);
            }
        });
        C2.setBounds(74, 148, 74, 74);
        jLayeredPane2.add(C2, javax.swing.JLayeredPane.DEFAULT_LAYER);

        C3.setText("C3");
        C3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                C3ActionPerformed(evt);
            }
        });
        C3.setBounds(148, 148, 74, 74);
        jLayeredPane2.add(C3, javax.swing.JLayeredPane.DEFAULT_LAYER);

        C4.setText("C4");
        C4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                C4ActionPerformed(evt);
            }
        });
        C4.setBounds(222, 148, 74, 74);
        jLayeredPane2.add(C4, javax.swing.JLayeredPane.DEFAULT_LAYER);

        C5.setText("C5");
        C5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                C5ActionPerformed(evt);
            }
        });
        C5.setBounds(296, 148, 74, 74);
        jLayeredPane2.add(C5, javax.swing.JLayeredPane.DEFAULT_LAYER);

        C6.setText("C6");
        C6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                C6ActionPerformed(evt);
            }
        });
        C6.setBounds(370, 148, 74, 74);
        jLayeredPane2.add(C6, javax.swing.JLayeredPane.DEFAULT_LAYER);

        C7.setText("C7");
        C7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                C7ActionPerformed(evt);
            }
        });
        C7.setBounds(444, 148, 74, 74);
        jLayeredPane2.add(C7, javax.swing.JLayeredPane.DEFAULT_LAYER);

        C8.setText("C8");
        C8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                C8ActionPerformed(evt);
            }
        });
        C8.setBounds(518, 148, 74, 74);
        jLayeredPane2.add(C8, javax.swing.JLayeredPane.DEFAULT_LAYER);

        C9.setText("C9");
        C9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                C9ActionPerformed(evt);
            }
        });
        C9.setBounds(592, 148, 74, 74);
        jLayeredPane2.add(C9, javax.swing.JLayeredPane.DEFAULT_LAYER);

        C10.setText("C10");
        C10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                C10ActionPerformed(evt);
            }
        });
        C10.setBounds(666, 148, 74, 74);
        jLayeredPane2.add(C10, javax.swing.JLayeredPane.DEFAULT_LAYER);

        C11.setText("C11");
        C11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                C11ActionPerformed(evt);
            }
        });
        C11.setBounds(740, 148, 74, 74);
        jLayeredPane2.add(C11, javax.swing.JLayeredPane.DEFAULT_LAYER);

        C12.setText("C12");
        C12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                C12ActionPerformed(evt);
            }
        });
        C12.setBounds(814, 148, 74, 74);
        jLayeredPane2.add(C12, javax.swing.JLayeredPane.DEFAULT_LAYER);

        D1.setText("D1");
        D1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                D1ActionPerformed(evt);
            }
        });
        D1.setBounds(0, 222, 74, 74);
        jLayeredPane2.add(D1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        D2.setText("D2");
        D2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                D2ActionPerformed(evt);
            }
        });
        D2.setBounds(74, 222, 74, 74);
        jLayeredPane2.add(D2, javax.swing.JLayeredPane.DEFAULT_LAYER);

        D3.setText("D3");
        D3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                D3ActionPerformed(evt);
            }
        });
        D3.setBounds(148, 222, 74, 74);
        jLayeredPane2.add(D3, javax.swing.JLayeredPane.DEFAULT_LAYER);

        D4.setText("D4");
        D4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                D4ActionPerformed(evt);
            }
        });
        D4.setBounds(222, 222, 74, 74);
        jLayeredPane2.add(D4, javax.swing.JLayeredPane.DEFAULT_LAYER);

        D5.setText("D5");
        D5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                D5ActionPerformed(evt);
            }
        });
        D5.setBounds(296, 222, 74, 74);
        jLayeredPane2.add(D5, javax.swing.JLayeredPane.DEFAULT_LAYER);

        D6.setText("D6");
        D6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                D6ActionPerformed(evt);
            }
        });
        D6.setBounds(370, 222, 74, 74);
        jLayeredPane2.add(D6, javax.swing.JLayeredPane.DEFAULT_LAYER);

        D7.setText("D7");
        D7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                D7ActionPerformed(evt);
            }
        });
        D7.setBounds(444, 222, 74, 74);
        jLayeredPane2.add(D7, javax.swing.JLayeredPane.DEFAULT_LAYER);

        D8.setText("D8");
        D8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                D8ActionPerformed(evt);
            }
        });
        D8.setBounds(518, 222, 74, 74);
        jLayeredPane2.add(D8, javax.swing.JLayeredPane.DEFAULT_LAYER);

        D9.setText("D9");
        D9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                D9ActionPerformed(evt);
            }
        });
        D9.setBounds(592, 222, 74, 74);
        jLayeredPane2.add(D9, javax.swing.JLayeredPane.DEFAULT_LAYER);

        D10.setText("D10");
        D10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                D10ActionPerformed(evt);
            }
        });
        D10.setBounds(666, 222, 74, 74);
        jLayeredPane2.add(D10, javax.swing.JLayeredPane.DEFAULT_LAYER);

        D11.setText("D11");
        D11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                D11ActionPerformed(evt);
            }
        });
        D11.setBounds(740, 222, 74, 74);
        jLayeredPane2.add(D11, javax.swing.JLayeredPane.DEFAULT_LAYER);

        D12.setText("D12");
        D12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                D12ActionPerformed(evt);
            }
        });
        D12.setBounds(814, 222, 74, 74);
        jLayeredPane2.add(D12, javax.swing.JLayeredPane.DEFAULT_LAYER);

        E1.setText("E1");
        E1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                E1ActionPerformed(evt);
            }
        });
        E1.setBounds(0, 296, 74, 74);
        jLayeredPane2.add(E1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        E2.setText("E2");
        E2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                E2ActionPerformed(evt);
            }
        });
        E2.setBounds(74, 296, 74, 74);
        jLayeredPane2.add(E2, javax.swing.JLayeredPane.DEFAULT_LAYER);

        E3.setText("E3");
        E3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                E3ActionPerformed(evt);
            }
        });
        E3.setBounds(148, 296, 74, 74);
        jLayeredPane2.add(E3, javax.swing.JLayeredPane.DEFAULT_LAYER);

        E4.setText("E4");
        E4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                E4ActionPerformed(evt);
            }
        });
        E4.setBounds(222, 296, 74, 74);
        jLayeredPane2.add(E4, javax.swing.JLayeredPane.DEFAULT_LAYER);

        E5.setText("E5");
        E5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                E5ActionPerformed(evt);
            }
        });
        E5.setBounds(296, 296, 74, 74);
        jLayeredPane2.add(E5, javax.swing.JLayeredPane.DEFAULT_LAYER);

        E6.setText("E6");
        E6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                E6ActionPerformed(evt);
            }
        });
        E6.setBounds(370, 296, 74, 74);
        jLayeredPane2.add(E6, javax.swing.JLayeredPane.DEFAULT_LAYER);

        E7.setText("E7");
        E7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                E7ActionPerformed(evt);
            }
        });
        E7.setBounds(444, 296, 74, 74);
        jLayeredPane2.add(E7, javax.swing.JLayeredPane.DEFAULT_LAYER);

        E8.setText("E8");
        E8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                E8ActionPerformed(evt);
            }
        });
        E8.setBounds(518, 296, 74, 74);
        jLayeredPane2.add(E8, javax.swing.JLayeredPane.DEFAULT_LAYER);

        E9.setText("E9");
        E9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                E9ActionPerformed(evt);
            }
        });
        E9.setBounds(592, 296, 74, 74);
        jLayeredPane2.add(E9, javax.swing.JLayeredPane.DEFAULT_LAYER);

        E10.setText("E10");
        E10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                E10ActionPerformed(evt);
            }
        });
        E10.setBounds(666, 296, 74, 74);
        jLayeredPane2.add(E10, javax.swing.JLayeredPane.DEFAULT_LAYER);

        E11.setText("E11");
        E11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                E11ActionPerformed(evt);
            }
        });
        E11.setBounds(740, 296, 74, 74);
        jLayeredPane2.add(E11, javax.swing.JLayeredPane.DEFAULT_LAYER);

        E12.setText("E12");
        E12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                E12ActionPerformed(evt);
            }
        });
        E12.setBounds(814, 296, 74, 74);
        jLayeredPane2.add(E12, javax.swing.JLayeredPane.DEFAULT_LAYER);

        F1.setText("F1");
        F1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                F1ActionPerformed(evt);
            }
        });
        F1.setBounds(0, 370, 74, 74);
        jLayeredPane2.add(F1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        F2.setText("F2");
        F2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                F2ActionPerformed(evt);
            }
        });
        F2.setBounds(74, 370, 74, 74);
        jLayeredPane2.add(F2, javax.swing.JLayeredPane.DEFAULT_LAYER);

        F3.setText("F3");
        F3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                F3ActionPerformed(evt);
            }
        });
        F3.setBounds(148, 370, 74, 74);
        jLayeredPane2.add(F3, javax.swing.JLayeredPane.DEFAULT_LAYER);

        F4.setText("F4");
        F4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                F4ActionPerformed(evt);
            }
        });
        F4.setBounds(222, 370, 74, 74);
        jLayeredPane2.add(F4, javax.swing.JLayeredPane.DEFAULT_LAYER);

        F5.setText("F5");
        F5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                F5ActionPerformed(evt);
            }
        });
        F5.setBounds(296, 370, 74, 74);
        jLayeredPane2.add(F5, javax.swing.JLayeredPane.DEFAULT_LAYER);

        F6.setText("F6");
        F6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                F6ActionPerformed(evt);
            }
        });
        F6.setBounds(370, 370, 74, 74);
        jLayeredPane2.add(F6, javax.swing.JLayeredPane.DEFAULT_LAYER);

        F7.setText("F7");
        F7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                F7ActionPerformed(evt);
            }
        });
        F7.setBounds(444, 370, 74, 74);
        jLayeredPane2.add(F7, javax.swing.JLayeredPane.DEFAULT_LAYER);

        F8.setText("F8");
        F8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                F8ActionPerformed(evt);
            }
        });
        F8.setBounds(518, 370, 74, 74);
        jLayeredPane2.add(F8, javax.swing.JLayeredPane.DEFAULT_LAYER);

        F9.setText("F9");
        F9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                F9ActionPerformed(evt);
            }
        });
        F9.setBounds(592, 370, 74, 74);
        jLayeredPane2.add(F9, javax.swing.JLayeredPane.DEFAULT_LAYER);

        F10.setText("F10");
        F10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                F10ActionPerformed(evt);
            }
        });
        F10.setBounds(666, 370, 74, 74);
        jLayeredPane2.add(F10, javax.swing.JLayeredPane.DEFAULT_LAYER);

        F11.setText("F11");
        F11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                F11ActionPerformed(evt);
            }
        });
        F11.setBounds(740, 370, 74, 74);
        jLayeredPane2.add(F11, javax.swing.JLayeredPane.DEFAULT_LAYER);

        F12.setText("F12");
        F12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                F12ActionPerformed(evt);
            }
        });
        F12.setBounds(814, 370, 74, 74);
        jLayeredPane2.add(F12, javax.swing.JLayeredPane.DEFAULT_LAYER);

        G1.setText("G1");
        G1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                G1ActionPerformed(evt);
            }
        });
        G1.setBounds(0, 444, 74, 74);
        jLayeredPane2.add(G1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        G2.setText("G2");
        G2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                G2ActionPerformed(evt);
            }
        });
        G2.setBounds(74, 444, 74, 74);
        jLayeredPane2.add(G2, javax.swing.JLayeredPane.DEFAULT_LAYER);

        G3.setText("G3");
        G3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                G3ActionPerformed(evt);
            }
        });
        G3.setBounds(148, 444, 74, 74);
        jLayeredPane2.add(G3, javax.swing.JLayeredPane.DEFAULT_LAYER);

        G4.setText("G4");
        G4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                G4ActionPerformed(evt);
            }
        });
        G4.setBounds(222, 444, 74, 74);
        jLayeredPane2.add(G4, javax.swing.JLayeredPane.DEFAULT_LAYER);

        G5.setText("G5");
        G5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                G5ActionPerformed(evt);
            }
        });
        G5.setBounds(296, 444, 74, 74);
        jLayeredPane2.add(G5, javax.swing.JLayeredPane.DEFAULT_LAYER);

        G6.setText("G6");
        G6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                G6ActionPerformed(evt);
            }
        });
        G6.setBounds(370, 444, 74, 74);
        jLayeredPane2.add(G6, javax.swing.JLayeredPane.DEFAULT_LAYER);

        G7.setText("G7");
        G7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                G7ActionPerformed(evt);
            }
        });
        G7.setBounds(444, 444, 74, 74);
        jLayeredPane2.add(G7, javax.swing.JLayeredPane.DEFAULT_LAYER);

        G8.setText("G8");
        G8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                G8ActionPerformed(evt);
            }
        });
        G8.setBounds(518, 444, 74, 74);
        jLayeredPane2.add(G8, javax.swing.JLayeredPane.DEFAULT_LAYER);

        G9.setText("G9");
        G9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                G9ActionPerformed(evt);
            }
        });
        G9.setBounds(592, 444, 74, 74);
        jLayeredPane2.add(G9, javax.swing.JLayeredPane.DEFAULT_LAYER);

        G10.setText("G10");
        G10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                G10ActionPerformed(evt);
            }
        });
        G10.setBounds(666, 444, 74, 74);
        jLayeredPane2.add(G10, javax.swing.JLayeredPane.DEFAULT_LAYER);

        G11.setText("G11");
        G11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                G11ActionPerformed(evt);
            }
        });
        G11.setBounds(740, 444, 74, 74);
        jLayeredPane2.add(G11, javax.swing.JLayeredPane.DEFAULT_LAYER);

        G12.setText("G12");
        G12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                G12ActionPerformed(evt);
            }
        });
        G12.setBounds(814, 444, 74, 74);
        jLayeredPane2.add(G12, javax.swing.JLayeredPane.DEFAULT_LAYER);

        H1.setText("H1");
        H1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                H1ActionPerformed(evt);
            }
        });
        H1.setBounds(0, 518, 74, 74);
        jLayeredPane2.add(H1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        H2.setText("H2");
        H2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                H2ActionPerformed(evt);
            }
        });
        H2.setBounds(74, 518, 74, 74);
        jLayeredPane2.add(H2, javax.swing.JLayeredPane.DEFAULT_LAYER);

        H3.setText("H3");
        H3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                H3ActionPerformed(evt);
            }
        });
        H3.setBounds(148, 518, 74, 74);
        jLayeredPane2.add(H3, javax.swing.JLayeredPane.DEFAULT_LAYER);

        H4.setText("H4");
        H4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                H4ActionPerformed(evt);
            }
        });
        H4.setBounds(222, 518, 74, 74);
        jLayeredPane2.add(H4, javax.swing.JLayeredPane.DEFAULT_LAYER);

        H5.setText("H5");
        H5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                H5ActionPerformed(evt);
            }
        });
        H5.setBounds(296, 518, 74, 74);
        jLayeredPane2.add(H5, javax.swing.JLayeredPane.DEFAULT_LAYER);

        H6.setText("H6");
        H6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                H6ActionPerformed(evt);
            }
        });
        H6.setBounds(370, 518, 74, 74);
        jLayeredPane2.add(H6, javax.swing.JLayeredPane.DEFAULT_LAYER);

        H7.setText("H7");
        H7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                H7ActionPerformed(evt);
            }
        });
        H7.setBounds(444, 518, 74, 74);
        jLayeredPane2.add(H7, javax.swing.JLayeredPane.DEFAULT_LAYER);

        H8.setText("H8");
        H8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                H8ActionPerformed(evt);
            }
        });
        H8.setBounds(518, 518, 74, 74);
        jLayeredPane2.add(H8, javax.swing.JLayeredPane.DEFAULT_LAYER);

        H9.setText("H9");
        H9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                H9ActionPerformed(evt);
            }
        });
        H9.setBounds(592, 518, 74, 74);
        jLayeredPane2.add(H9, javax.swing.JLayeredPane.DEFAULT_LAYER);

        H10.setText("H10");
        H10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                H10ActionPerformed(evt);
            }
        });
        H10.setBounds(666, 518, 74, 74);
        jLayeredPane2.add(H10, javax.swing.JLayeredPane.DEFAULT_LAYER);

        H11.setText("H11");
        H11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                H11ActionPerformed(evt);
            }
        });
        H11.setBounds(740, 518, 74, 74);
        jLayeredPane2.add(H11, javax.swing.JLayeredPane.DEFAULT_LAYER);

        H12.setText("H12");
        H12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                H12ActionPerformed(evt);
            }
        });
        H12.setBounds(814, 518, 74, 74);
        jLayeredPane2.add(H12, javax.swing.JLayeredPane.DEFAULT_LAYER);

        I1.setText("I1");
        I1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                I1ActionPerformed(evt);
            }
        });
        I1.setBounds(0, 592, 74, 74);
        jLayeredPane2.add(I1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        I2.setText("I2");
        I2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                I2ActionPerformed(evt);
            }
        });
        I2.setBounds(74, 592, 74, 74);
        jLayeredPane2.add(I2, javax.swing.JLayeredPane.DEFAULT_LAYER);

        I3.setText("I3");
        I3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                I3ActionPerformed(evt);
            }
        });
        I3.setBounds(148, 592, 74, 74);
        jLayeredPane2.add(I3, javax.swing.JLayeredPane.DEFAULT_LAYER);

        I4.setText("I4");
        I4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                I4ActionPerformed(evt);
            }
        });
        I4.setBounds(222, 592, 74, 74);
        jLayeredPane2.add(I4, javax.swing.JLayeredPane.DEFAULT_LAYER);

        I5.setText("I5");
        I5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                I5ActionPerformed(evt);
            }
        });
        I5.setBounds(296, 592, 74, 74);
        jLayeredPane2.add(I5, javax.swing.JLayeredPane.DEFAULT_LAYER);

        I6.setText("I6");
        I6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                I6ActionPerformed(evt);
            }
        });
        I6.setBounds(370, 592, 74, 74);
        jLayeredPane2.add(I6, javax.swing.JLayeredPane.DEFAULT_LAYER);

        I7.setText("I7");
        I7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                I7ActionPerformed(evt);
            }
        });
        I7.setBounds(444, 592, 74, 74);
        jLayeredPane2.add(I7, javax.swing.JLayeredPane.DEFAULT_LAYER);

        I8.setText("I8");
        I8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                I8ActionPerformed(evt);
            }
        });
        I8.setBounds(518, 592, 74, 74);
        jLayeredPane2.add(I8, javax.swing.JLayeredPane.DEFAULT_LAYER);

        I9.setText("I9");
        I9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                I9ActionPerformed(evt);
            }
        });
        I9.setBounds(592, 592, 74, 74);
        jLayeredPane2.add(I9, javax.swing.JLayeredPane.DEFAULT_LAYER);

        I10.setText("I10");
        I10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                I10ActionPerformed(evt);
            }
        });
        I10.setBounds(666, 592, 74, 74);
        jLayeredPane2.add(I10, javax.swing.JLayeredPane.DEFAULT_LAYER);

        I11.setText("I11");
        I11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                I11ActionPerformed(evt);
            }
        });
        I11.setBounds(740, 592, 74, 74);
        jLayeredPane2.add(I11, javax.swing.JLayeredPane.DEFAULT_LAYER);

        I12.setText("I12");
        I12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                I12ActionPerformed(evt);
            }
        });
        I12.setBounds(814, 592, 74, 74);
        jLayeredPane2.add(I12, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLayeredPane2.setBounds(0, 0, 888, 666);
        jLayeredPane1.add(jLayeredPane2, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLayeredPane3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLayeredPane3.setBounds(888, 0, 312, 666);
        jLayeredPane1.add(jLayeredPane3, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1200, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 666, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void I11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_I11ActionPerformed
        this.text += "106,";
        System.out.println(text);
    }//GEN-LAST:event_I11ActionPerformed

    private void I10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_I10ActionPerformed
        this.text += "105,";
        System.out.println(text);
    }//GEN-LAST:event_I10ActionPerformed

    private void I9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_I9ActionPerformed
        this.text += "104,";
        System.out.println(text);
    }//GEN-LAST:event_I9ActionPerformed

    private void I8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_I8ActionPerformed
        this.text += "103,";
        System.out.println(text);
    }//GEN-LAST:event_I8ActionPerformed

    private void I7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_I7ActionPerformed
        this.text += "102,";
        System.out.println(text);
    }//GEN-LAST:event_I7ActionPerformed

    private void I6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_I6ActionPerformed
        this.text += "101,";
        System.out.println(text);
    }//GEN-LAST:event_I6ActionPerformed

    private void I5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_I5ActionPerformed
        this.text += "100,";
        System.out.println(text);
    }//GEN-LAST:event_I5ActionPerformed

    private void I4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_I4ActionPerformed
        this.text += "99,";
        System.out.println(text);
    }//GEN-LAST:event_I4ActionPerformed

    private void I3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_I3ActionPerformed
        this.text += "98,";
        System.out.println(text);
    }//GEN-LAST:event_I3ActionPerformed

    private void I2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_I2ActionPerformed
        this.text += "97,";
        System.out.println(text);
    }//GEN-LAST:event_I2ActionPerformed

    private void I1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_I1ActionPerformed
        this.text += "96,";
        System.out.println(text);
    }//GEN-LAST:event_I1ActionPerformed

    private void H12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_H12ActionPerformed
        this.text += "95,";
        System.out.println(text);
    }//GEN-LAST:event_H12ActionPerformed

    private void H11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_H11ActionPerformed
        this.text += "94,";
        System.out.println(text);
    }//GEN-LAST:event_H11ActionPerformed

    private void H10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_H10ActionPerformed
        this.text += "93,";
        System.out.println(text);
    }//GEN-LAST:event_H10ActionPerformed

    private void H9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_H9ActionPerformed
        this.text += "92,";
        System.out.println(text);
    }//GEN-LAST:event_H9ActionPerformed

    private void H8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_H8ActionPerformed
        this.text += "91,";
        System.out.println(text);
    }//GEN-LAST:event_H8ActionPerformed

    private void H7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_H7ActionPerformed
        this.text += "90,";
        System.out.println(text);
    }//GEN-LAST:event_H7ActionPerformed

    private void H6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_H6ActionPerformed
        this.text += "89,";
        System.out.println(text);
    }//GEN-LAST:event_H6ActionPerformed

    private void H5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_H5ActionPerformed
        this.text += "88,";
        System.out.println(text);
    }//GEN-LAST:event_H5ActionPerformed

    private void H4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_H4ActionPerformed
        this.text += "87,";
        System.out.println(text);
    }//GEN-LAST:event_H4ActionPerformed

    private void H3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_H3ActionPerformed
        this.text += "86,";
        System.out.println(text);
    }//GEN-LAST:event_H3ActionPerformed

    private void H2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_H2ActionPerformed
        this.text += "85,";
        System.out.println(text);
    }//GEN-LAST:event_H2ActionPerformed

    private void H1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_H1ActionPerformed
        this.text += "84,";
        System.out.println(text);
    }//GEN-LAST:event_H1ActionPerformed

    private void G12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_G12ActionPerformed
        this.text += "83,";
        System.out.println(text);
    }//GEN-LAST:event_G12ActionPerformed

    private void G11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_G11ActionPerformed
        this.text += "82,";
        System.out.println(text);
    }//GEN-LAST:event_G11ActionPerformed

    private void G10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_G10ActionPerformed
        this.text += "81,";
        System.out.println(text);
    }//GEN-LAST:event_G10ActionPerformed

    private void G9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_G9ActionPerformed
        this.text += "80,";
        System.out.println(text);
    }//GEN-LAST:event_G9ActionPerformed

    private void G8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_G8ActionPerformed
        this.text += "79,";
        System.out.println(text);
    }//GEN-LAST:event_G8ActionPerformed

    private void G7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_G7ActionPerformed
        this.text += "78,";
        System.out.println(text);
    }//GEN-LAST:event_G7ActionPerformed

    private void G6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_G6ActionPerformed
        this.text += "77,";
        System.out.println(text);
    }//GEN-LAST:event_G6ActionPerformed

    private void G5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_G5ActionPerformed
        this.text += "76,";
        System.out.println(text);
    }//GEN-LAST:event_G5ActionPerformed

    private void G4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_G4ActionPerformed
        this.text += "75,";
        System.out.println(text);
    }//GEN-LAST:event_G4ActionPerformed

    private void G3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_G3ActionPerformed
        this.text += "74,";
        System.out.println(text);
    }//GEN-LAST:event_G3ActionPerformed

    private void G2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_G2ActionPerformed
        this.text += "73,";
        System.out.println(text);
    }//GEN-LAST:event_G2ActionPerformed

    private void G1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_G1ActionPerformed
        this.text += "72,";
        System.out.println(text);
    }//GEN-LAST:event_G1ActionPerformed

    private void F12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_F12ActionPerformed
        this.text += "71,";
        System.out.println(text);
    }//GEN-LAST:event_F12ActionPerformed

    private void F11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_F11ActionPerformed
        this.text += "70,";
        System.out.println(text);
    }//GEN-LAST:event_F11ActionPerformed

    private void F10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_F10ActionPerformed
        this.text += "69,";
        System.out.println(text);
    }//GEN-LAST:event_F10ActionPerformed

    private void F9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_F9ActionPerformed
        this.text += "68,";
        System.out.println(text);
    }//GEN-LAST:event_F9ActionPerformed

    private void F8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_F8ActionPerformed
        this.text += "67,";
        System.out.println(text);
    }//GEN-LAST:event_F8ActionPerformed

    private void F7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_F7ActionPerformed
        this.text += "66,";
        System.out.println(text);
    }//GEN-LAST:event_F7ActionPerformed

    private void F6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_F6ActionPerformed
        this.text += "65,";
        System.out.println(text);
    }//GEN-LAST:event_F6ActionPerformed

    private void F5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_F5ActionPerformed
        this.text += "64,";
        System.out.println(text);
    }//GEN-LAST:event_F5ActionPerformed

    private void F4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_F4ActionPerformed
        this.text += "63,";
        System.out.println(text);
    }//GEN-LAST:event_F4ActionPerformed

    private void F3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_F3ActionPerformed
        this.text += "62,";
        System.out.println(text);
    }//GEN-LAST:event_F3ActionPerformed

    private void F2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_F2ActionPerformed
        this.text += "61,";
        System.out.println(text);
    }//GEN-LAST:event_F2ActionPerformed

    private void F1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_F1ActionPerformed
        this.text += "60,";
        System.out.println(text);
    }//GEN-LAST:event_F1ActionPerformed

    private void E12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_E12ActionPerformed
        this.text += "59,";
        System.out.println(text);
    }//GEN-LAST:event_E12ActionPerformed

    private void E11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_E11ActionPerformed
        this.text += "58,";
        System.out.println(text);
    }//GEN-LAST:event_E11ActionPerformed

    private void E10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_E10ActionPerformed
        this.text += "57,";
        System.out.println(text);
    }//GEN-LAST:event_E10ActionPerformed

    private void E9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_E9ActionPerformed
        this.text += "56,";
        System.out.println(text);
    }//GEN-LAST:event_E9ActionPerformed

    private void E8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_E8ActionPerformed
        this.text += "55,";
        System.out.println(text);
    }//GEN-LAST:event_E8ActionPerformed

    private void E7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_E7ActionPerformed
        this.text += "54,";
        System.out.println(text);
    }//GEN-LAST:event_E7ActionPerformed

    private void E6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_E6ActionPerformed
        this.text += "53,";
        System.out.println(text);
    }//GEN-LAST:event_E6ActionPerformed

    private void E5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_E5ActionPerformed
        this.text += "52,";
        System.out.println(text);
    }//GEN-LAST:event_E5ActionPerformed

    private void E4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_E4ActionPerformed
        this.text += "51,";
        System.out.println(text);
    }//GEN-LAST:event_E4ActionPerformed

    private void E3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_E3ActionPerformed
        this.text += "50,";
        System.out.println(text);
    }//GEN-LAST:event_E3ActionPerformed

    private void E2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_E2ActionPerformed
        this.text += "49,";
        System.out.println(text);
    }//GEN-LAST:event_E2ActionPerformed

    private void E1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_E1ActionPerformed
        this.text += "48,";
        System.out.println(text);
    }//GEN-LAST:event_E1ActionPerformed

    private void D12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_D12ActionPerformed
        this.text += "47,";
        System.out.println(text);
    }//GEN-LAST:event_D12ActionPerformed

    private void D11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_D11ActionPerformed
        this.text += "46,";
        System.out.println(text);
    }//GEN-LAST:event_D11ActionPerformed

    private void D10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_D10ActionPerformed
        this.text += "45,";
        System.out.println(text);
    }//GEN-LAST:event_D10ActionPerformed

    private void D9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_D9ActionPerformed
        this.text += "44,";
        System.out.println(text);
    }//GEN-LAST:event_D9ActionPerformed

    private void D8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_D8ActionPerformed
        this.text += "43,";
        System.out.println(text);
    }//GEN-LAST:event_D8ActionPerformed

    private void D7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_D7ActionPerformed
        this.text += "42,";
        System.out.println(text);
    }//GEN-LAST:event_D7ActionPerformed

    private void D6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_D6ActionPerformed
        this.text += "41,";
        System.out.println(text);
    }//GEN-LAST:event_D6ActionPerformed

    private void D5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_D5ActionPerformed
        this.text += "40,";
        System.out.println(text);
    }//GEN-LAST:event_D5ActionPerformed

    private void D4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_D4ActionPerformed
        this.text += "39,";
        System.out.println(text);
    }//GEN-LAST:event_D4ActionPerformed

    private void D3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_D3ActionPerformed
        this.text += "38,";
        System.out.println(text);
    }//GEN-LAST:event_D3ActionPerformed

    private void D2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_D2ActionPerformed
        this.text += "37,";
        System.out.println(text);
    }//GEN-LAST:event_D2ActionPerformed

    private void D1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_D1ActionPerformed
        this.text += "36,";
        System.out.println(text);
    }//GEN-LAST:event_D1ActionPerformed

    private void C12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_C12ActionPerformed
        this.text += "35,";
        System.out.println(text);
    }//GEN-LAST:event_C12ActionPerformed

    private void C11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_C11ActionPerformed
        this.text += "34,";
        System.out.println(text);
    }//GEN-LAST:event_C11ActionPerformed

    private void C10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_C10ActionPerformed
        this.text += "33,";
        System.out.println(text);
    }//GEN-LAST:event_C10ActionPerformed

    private void C9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_C9ActionPerformed
        this.text += "32,";
        System.out.println(text);
    }//GEN-LAST:event_C9ActionPerformed

    private void C8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_C8ActionPerformed
        this.text += "31,";
        System.out.println(text);
    }//GEN-LAST:event_C8ActionPerformed

    private void C7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_C7ActionPerformed
        this.text += "30,";
        System.out.println(text);
    }//GEN-LAST:event_C7ActionPerformed

    private void C6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_C6ActionPerformed
        this.text += "29,";
        System.out.println(text);
    }//GEN-LAST:event_C6ActionPerformed

    private void C5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_C5ActionPerformed
        this.text += "28,";
        System.out.println(text);
    }//GEN-LAST:event_C5ActionPerformed

    private void C4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_C4ActionPerformed
        this.text += "27,";
        System.out.println(text);
    }//GEN-LAST:event_C4ActionPerformed

    private void C3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_C3ActionPerformed
        this.text += "26,";
        System.out.println(text);
    }//GEN-LAST:event_C3ActionPerformed

    private void C2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_C2ActionPerformed
        this.text += "25,";
        System.out.println(text);
    }//GEN-LAST:event_C2ActionPerformed

    private void C1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_C1ActionPerformed
        this.text += "24,";
        System.out.println(text);
    }//GEN-LAST:event_C1ActionPerformed

    private void B12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B12ActionPerformed
        this.text += "23,";
        System.out.println(text);
    }//GEN-LAST:event_B12ActionPerformed

    private void B11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B11ActionPerformed
        this.text += "22,";
        System.out.println(text);
    }//GEN-LAST:event_B11ActionPerformed

    private void B10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B10ActionPerformed
        this.text += "21,";
        System.out.println(text);
    }//GEN-LAST:event_B10ActionPerformed

    private void B9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B9ActionPerformed
        this.text += "20,";
        System.out.println(text);
    }//GEN-LAST:event_B9ActionPerformed

    private void B8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B8ActionPerformed
        this.text += "19,";
        System.out.println(text);
    }//GEN-LAST:event_B8ActionPerformed

    private void B7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B7ActionPerformed
        this.text += "18,";
        System.out.println(text);
    }//GEN-LAST:event_B7ActionPerformed

    private void B6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B6ActionPerformed
        this.text += "17,";
        System.out.println(text);
    }//GEN-LAST:event_B6ActionPerformed

    private void B5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B5ActionPerformed
        this.text += "16,";
        System.out.println(text);
    }//GEN-LAST:event_B5ActionPerformed

    private void B4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B4ActionPerformed
        this.text += "15,";
        System.out.println(text);
    }//GEN-LAST:event_B4ActionPerformed

    private void B3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B3ActionPerformed
        this.text += "14,";
        System.out.println(text);
    }//GEN-LAST:event_B3ActionPerformed

    private void B2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B2ActionPerformed
this.text += "13,";
        System.out.println(text);
    }//GEN-LAST:event_B2ActionPerformed

    private void B1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B1ActionPerformed
this.text += "12,";
        System.out.println(text);
    }//GEN-LAST:event_B1ActionPerformed

    private void A12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_A12ActionPerformed
this.text += "11,";
        System.out.println(text);
    }//GEN-LAST:event_A12ActionPerformed

    private void A11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_A11ActionPerformed
this.text += "10,";
        System.out.println(text);
    }//GEN-LAST:event_A11ActionPerformed

    private void A10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_A10ActionPerformed
this.text += "9,";
        System.out.println(text);
    }//GEN-LAST:event_A10ActionPerformed

    private void A9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_A9ActionPerformed
this.text += "8,";
        System.out.println(text);
    }//GEN-LAST:event_A9ActionPerformed

    private void A8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_A8ActionPerformed
this.text += "7,";
        System.out.println(text);
    }//GEN-LAST:event_A8ActionPerformed

    private void A7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_A7ActionPerformed
this.text += "6,";
        System.out.println(text);
    }//GEN-LAST:event_A7ActionPerformed

    private void A6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_A6ActionPerformed
this.text += "5,";
        System.out.println(text);
    }//GEN-LAST:event_A6ActionPerformed

    private void A5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_A5ActionPerformed
this.text += "4,";
        System.out.println(text);
    }//GEN-LAST:event_A5ActionPerformed

    private void A4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_A4ActionPerformed
this.text += "3,";
        System.out.println(text);
    }//GEN-LAST:event_A4ActionPerformed

    private void A3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_A3ActionPerformed
        this.text += "2,";
        System.out.println(text);
    }//GEN-LAST:event_A3ActionPerformed

    private void A2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_A2ActionPerformed
        this.text += "1,";
        System.out.println(text);
    }//GEN-LAST:event_A2ActionPerformed

    private void A1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_A1ActionPerformed
        this.text += "0,";
        System.out.println(text);
    }//GEN-LAST:event_A1ActionPerformed

    private void I12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_I12ActionPerformed
        // TODO add your handling code here:
        this.text += "107,";
        System.out.println(text);
    }//GEN-LAST:event_I12ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(game.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(game.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(game.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(game.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new game().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton A1;
    private javax.swing.JButton A10;
    private javax.swing.JButton A11;
    private javax.swing.JButton A12;
    private javax.swing.JButton A2;
    private javax.swing.JButton A3;
    private javax.swing.JButton A4;
    private javax.swing.JButton A5;
    private javax.swing.JButton A6;
    private javax.swing.JButton A7;
    private javax.swing.JButton A8;
    private javax.swing.JButton A9;
    private javax.swing.JButton B1;
    private javax.swing.JButton B10;
    private javax.swing.JButton B11;
    private javax.swing.JButton B12;
    private javax.swing.JButton B2;
    private javax.swing.JButton B3;
    private javax.swing.JButton B4;
    private javax.swing.JButton B5;
    private javax.swing.JButton B6;
    private javax.swing.JButton B7;
    private javax.swing.JButton B8;
    private javax.swing.JButton B9;
    private javax.swing.JButton C1;
    private javax.swing.JButton C10;
    private javax.swing.JButton C11;
    private javax.swing.JButton C12;
    private javax.swing.JButton C2;
    private javax.swing.JButton C3;
    private javax.swing.JButton C4;
    private javax.swing.JButton C5;
    private javax.swing.JButton C6;
    private javax.swing.JButton C7;
    private javax.swing.JButton C8;
    private javax.swing.JButton C9;
    private javax.swing.JButton D1;
    private javax.swing.JButton D10;
    private javax.swing.JButton D11;
    private javax.swing.JButton D12;
    private javax.swing.JButton D2;
    private javax.swing.JButton D3;
    private javax.swing.JButton D4;
    private javax.swing.JButton D5;
    private javax.swing.JButton D6;
    private javax.swing.JButton D7;
    private javax.swing.JButton D8;
    private javax.swing.JButton D9;
    private javax.swing.JButton E1;
    private javax.swing.JButton E10;
    private javax.swing.JButton E11;
    private javax.swing.JButton E12;
    private javax.swing.JButton E2;
    private javax.swing.JButton E3;
    private javax.swing.JButton E4;
    private javax.swing.JButton E5;
    private javax.swing.JButton E6;
    private javax.swing.JButton E7;
    private javax.swing.JButton E8;
    private javax.swing.JButton E9;
    private javax.swing.JButton F1;
    private javax.swing.JButton F10;
    private javax.swing.JButton F11;
    private javax.swing.JButton F12;
    private javax.swing.JButton F2;
    private javax.swing.JButton F3;
    private javax.swing.JButton F4;
    private javax.swing.JButton F5;
    private javax.swing.JButton F6;
    private javax.swing.JButton F7;
    private javax.swing.JButton F8;
    private javax.swing.JButton F9;
    private javax.swing.JButton G1;
    private javax.swing.JButton G10;
    private javax.swing.JButton G11;
    private javax.swing.JButton G12;
    private javax.swing.JButton G2;
    private javax.swing.JButton G3;
    private javax.swing.JButton G4;
    private javax.swing.JButton G5;
    private javax.swing.JButton G6;
    private javax.swing.JButton G7;
    private javax.swing.JButton G8;
    private javax.swing.JButton G9;
    private javax.swing.JButton H1;
    private javax.swing.JButton H10;
    private javax.swing.JButton H11;
    private javax.swing.JButton H2;
    private javax.swing.JButton H3;
    private javax.swing.JButton H4;
    private javax.swing.JButton H5;
    private javax.swing.JButton H6;
    private javax.swing.JButton H7;
    private javax.swing.JButton H8;
    private javax.swing.JButton H9;
    private javax.swing.JButton I1;
    private javax.swing.JButton I10;
    private javax.swing.JButton I12;
    private javax.swing.JButton I2;
    private javax.swing.JButton I4;
    private javax.swing.JButton I7;
    private javax.swing.JButton I8;
    private javax.swing.JButton I9;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JLayeredPane jLayeredPane2;
    private javax.swing.JLayeredPane jLayeredPane3;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
